<?php
/**
 * @file
 * The drupal module file for upei_roblib_ill module
 */
function upei_roblib_ill_menu() {

  $items = array();

  $items['admin/settings/roblibill'] = array(
    'title' => 'UPEI Roblib ILL settings',
    'description' => 'Conifiguration for the UPEI ILL forms',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('upei_roblib_ill_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['upei/roblib/ill'] = array(
    'title' => 'UPEI ILL Form',
    'description' => 'The entry point for the UPEI ILL forms',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('upei_roblib_ill_form'),
    'access arguments' => array('access content'),
    'file' => 'includes/form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function upei_roblib_ill_doi_callback($form, &$form_state) {
  module_load_include('inc', 'upei_roblib_ill', 'includes/doi');
  $form = upei_roblib_ill_doi_get_data($form, $form_state['values']['doi']);
  return $form;
}

/**
 * Implements hook_views_api().
 */
function upei_roblib_ill_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'upei_roblib_ill') . '/views',
  );
}

/**
 * Implements hook_views_data().
 */
function upei_roblib_ill_views_data() {
  $data['upei_roblib_ill_request']['table']['group'] = t('UPEI Roblib ILL');
  $data['upei_roblib_ill_request']['table']['base'] = array(
    'field' => 'id',
    'title' => t('UPEI Roblib ILL Request'),
    'help' => t('Table for logging ILL Request'),
    'weight' => -10,
  );

  $data['upei_roblib_ill_request']['patron_id'] = array(
    'title' => t('Patron or Campus ID'),
    'help' => t('Patron or Campus ID.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  $data['upei_roblib_ill_request']['id'] = array(
    'title' => t('Unique ID for an ILL request'),
    'help' => t('Unique ID for an ILL request.'),
    'field' => array(
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_numeric',
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
  );

  $data['upei_roblib_ill_request']['patron_email'] = array(
    'title' => t('Patron Email Address'),
    'help' => t('Patron Email Address.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['patron_lastname'] = array(
    'title' => t('Patron Lastname'),
    'help' => t('Patron Lastname.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  $data['upei_roblib_ill_request']['patron_firstname'] = array(
    'title' => t('Patron Firstame'),
    'help' => t('Patron Firstname.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['patron_department'] = array(
    'title' => t('Patron Department'),
    'help' => t('Patron Department.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['patron_type'] = array(
    'title' => t('Patron Type'),
    'help' => t('Patron Type.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['author'] = array(
    'title' => t('Authors name'),
    'help' => t('Authors Fullname.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['title'] = array(
    'title' => t('Book or Journal Title'),
    'help' => t('Book or Patron Title.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['atitle'] = array(
    'title' => t('Article or Chapter Title'),
    'help' => t('Article or Chapter Title.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['issn'] = array(
    'title' => t('ISSN'),
    'help' => t('ISSN.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['isbn'] = array(
    'title' => t('ISBN'),
    'help' => t('ISBN.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['article_author'] = array(
    'title' => t('Article or Chapter author'),
    'help' => t('Article or Chapter author.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['citation_date'] = array(
    'title' => t('The date of the article'),
    'help' => t('Article Date.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['pages_requested'] = array(
    'title' => t('The pages requested'),
    'help' => t('The pages requested.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['volume'] = array(
    'title' => t('Volume'),
    'help' => t('Volume.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['issue'] = array(
    'title' => t('Issue'),
    'help' => t('Issue.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['genre'] = array(
    'title' => t('Article or Chapter author'),
    'help' => t('Article or Chapter author.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['relais_request_id'] = array(
    'title' => t('The Relais request id'),
    'help' => t('The Relais request id.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['relais_message'] = array(
    'title' => t('The reason a request failed. '),
    'help' => t('The reason a request failed.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );
  $data['upei_roblib_ill_request']['notes'] = array(
    'title' => t('The notes related to this request'),
    'help' => t('The notes related to this request.'),
    'field' => array(
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_string',
    ),
    'argument' => array(
      'handler' => 'views_handler_argument_string',
    ),
  );

  $data['upei_roblib_ill_request']['time_submitted'] = array(
    'title' => t('The Date and Time a request was submitted'),
    'help' => t('The Date and Time a request was submitted.'),
    'field' => array(
      'handler' => 'views_handler_field_date',
      'click sortable' => TRUE,
    ),
    'sort' => array(
      'handler' => 'views_handler_sort_date',
    ),
    'filter' => array(
      'handler' => 'views_handler_filter_date',
    ),
  );

  return $data;
}






