<?php
/**
 * @file
 * The drupal module file for upei_roblib_ill module
 */
function upei_roblib_ill_menu() {

  $items = [];

  $items['admin/settings/roblibill'] = [
    'title' => 'UPEI Roblib ILL settings',
    'description' => 'Conifiguration for the UPEI ILL forms',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['upei_roblib_ill_admin_form'],
    'access arguments' => ['access administration pages'],
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  ];
  $items['upei/roblib/ill'] = [
    'title' => 'UPEI ILL Form',
    'description' => 'The entry point for the UPEI ILL forms',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['upei_roblib_ill_form'],
    'access arguments' => ['access content'],
    'file' => 'includes/form.inc',
    'type' => MENU_NORMAL_ITEM,
  ];
  $items['upei/roblib/ill/finished'] = [
    'title' => 'UPEI ILL Request',
    'description' => 'Redirect to this page after form is submitted',
    'page callback' => 'upei_roblib_ill_form_redirect',
    'access arguments' => ['access content'],
    'file' => 'includes/form.inc',
    'type' => MENU_NORMAL_ITEM,
  ];
  return $items;
}

/**
 * Get the metadata associated with this DOI.
 *
 * @param $form
 * @param $form_state
 *
 * @return array
 */
function upei_roblib_ill_doi_callback($form, &$form_state) {
  module_load_include('inc', 'upei_roblib_ill', 'includes/doi');
  $form = upei_roblib_ill_doi_get_data($form, $form_state['values']['doi']);
  return $form;
}

/**
 * Implements hook_views_api().
 */
function upei_roblib_ill_views_api() {
  return [
    'api' => 3,
    'path' => drupal_get_path('module', 'upei_roblib_ill') . '/views',
  ];
}

/**
 * Implements hook_views_data().
 */
function upei_roblib_ill_views_data() {
  $data['upei_roblib_ill_request']['table']['group'] = t('UPEI Roblib ILL');
  $data['upei_roblib_ill_request']['table']['base'] = [
    'field' => 'id',
    'title' => t('UPEI Roblib ILL Request'),
    'help' => t('Table for logging ILL Request'),
    'weight' => -10,
  ];

  $data['upei_roblib_ill_request']['patron_id'] = [
    'title' => t('Patron or Campus ID'),
    'help' => t('Patron or Campus ID.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];

  $data['upei_roblib_ill_request']['id'] = [
    'title' => t('Unique ID for an ILL request'),
    'help' => t('Unique ID for an ILL request.'),
    'field' => [
      'handler' => 'views_handler_field_numeric',
      'click sortable' => TRUE,
    ],
    'filter' => [
      'handler' => 'views_handler_filter_numeric',
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
  ];

  $data['upei_roblib_ill_request']['patron_email'] = [
    'title' => t('Patron Email Address'),
    'help' => t('Patron Email Address.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['patron_lastname'] = [
    'title' => t('Patron Lastname'),
    'help' => t('Patron Lastname.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];

  $data['upei_roblib_ill_request']['patron_firstname'] = [
    'title' => t('Patron Firstame'),
    'help' => t('Patron Firstname.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['patron_department'] = [
    'title' => t('Patron Department'),
    'help' => t('Patron Department.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['patron_type'] = [
    'title' => t('Patron Type'),
    'help' => t('Patron Type.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['author'] = [
    'title' => t('Authors name'),
    'help' => t('Authors Fullname.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['title'] = [
    'title' => t('Book or Journal Title'),
    'help' => t('Book or Patron Title.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['atitle'] = [
    'title' => t('Article or Chapter Title'),
    'help' => t('Article or Chapter Title.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['issn'] = [
    'title' => t('ISSN'),
    'help' => t('ISSN.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['isbn'] = [
    'title' => t('ISBN'),
    'help' => t('ISBN.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['article_author'] = [
    'title' => t('Article or Chapter author'),
    'help' => t('Article or Chapter author.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['citation_date'] = [
    'title' => t('The date of the article'),
    'help' => t('Article Date.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['pages_requested'] = [
    'title' => t('The pages requested'),
    'help' => t('The pages requested.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['volume'] = [
    'title' => t('Volume'),
    'help' => t('Volume.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['issue'] = [
    'title' => t('Issue'),
    'help' => t('Issue.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['genre'] = [
    'title' => t('Genre'),
    'help' => t('The type of item requested.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['doi'] = [
    'title' => t('DOI'),
    'help' => t('DOI.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['relais_request_id'] = [
    'title' => t('The Relais request id'),
    'help' => t('The Relais request id.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['relais_message'] = [
    'title' => t('The reason a request failed.'),
    'help' => t('The reason a request failed.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];
  $data['upei_roblib_ill_request']['notes'] = [
    'title' => t('The notes related to this request'),
    'help' => t('The notes related to this request.'),
    'field' => [
      'handler' => 'views_handler_field',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_string',
    ],
    'argument' => [
      'handler' => 'views_handler_argument_string',
    ],
  ];

  $data['upei_roblib_ill_request']['time_submitted'] = [
    'title' => t('The Date and Time a request was submitted'),
    'help' => t('The Date and Time a request was submitted.'),
    'field' => [
      'handler' => 'views_handler_field_date',
      'click sortable' => TRUE,
    ],
    'sort' => [
      'handler' => 'views_handler_sort_date',
    ],
    'filter' => [
      'handler' => 'views_handler_filter_date',
    ],
  ];

  return $data;
}






